### ISSUE TITLE
Not able to extract link.

### ISSUE THREAD

**Issue by SahilKhachi** [devandsev/YoutubeDirectLinkExtractor#10]
Any update on cantExtractFmtStreamMap issue ?

**Comment by wilz05** [comment]
@SahilKhachi  I believe youtube has changed its output parameters  
 [this link]  ("https://www.youtube.com/get_video_info?video_id=") doesn't  provide **url_encoded_fmt_stream_map** output anymore .

**Comment by fishercraigj** [comment]
Bump, same issue

**Comment by fishercraigj** [comment]
@SahilKhachi @wilz05 - Have you guys come up with a work around or other solution?

**Comment by wilz05** [comment]
Yes, This Library needs an Update,I have used YoutubeDirectLinkExtractor code itself + using  SwiftyJSON and Alamofire library by customizing few lines 
for now this solution works for me
 
` private func firstPlayable(from urls: [String]) -> String? {
        for urlString in urls {
            guard let url = URL(string: urlString) else {
                continue
            }
            let asset = AVAsset(url: url)
            if asset.isPlayable {
                return urlString
            }
        }
         return nil
    }`


`private func videoId(from url: URL) -> String? {
        guard let host = url.host else {
            return nil
        }
        let components = url.pathComponents
        switch host {
        case _ where host.contains("youtu.be"):
            return components[1]
        case _ where host.contains("m.youtube.com"):
            return url.absoluteString.components(separatedBy: "?").last?.queryComponents()["v"]
        case _ where host.contains("youtube.com")
            && components[1] == "embed":
            return components[2]
        case _ where host.contains("youtube.com")
            && components[1] != "embed":
            return url.query?.queryComponents()["v"]
        default:
            return nil
        }
    }`

`func getYoutubeVideoLink  (youtubeLink : String,completion:@escaping (_ url:  String , _ success: Bool)-> Void)
    {
        let id = videoId(from: URL(string: youtubeLink)!)!
        // this function is alternative to https://github.com/devandsev/YoutubeDirectLinkExtractor
        let url  = URL(string: "https://www.youtube.com/get_video_info?video_id=\(id)") //o1YA_6tXs5E
        let userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
        var request = URLRequest(url:url!)
        request.httpMethod = "GET"
        request.addValue(userAgent, forHTTPHeaderField: "User-Agent")
        request.addValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")
        Alamofire.request(request ).debugLog().responseData { response in
            print("All Response Info: \(response)")
            if let data = response.result.value {
                guard let dataString = String(data: data, encoding: .utf8) else {
                    print("Cannot cantConvertDataToString")
                    completion("", false)
                    // completion([], Error.cantConvertDataToString)
                    return
                }
                var pairs: [String: String] = [:]
                for pair in dataString.components(separatedBy: "&") {
                    let pairArr = pair.components(separatedBy: "=")
                    guard pairArr.count == 2,
                        let key = pairArr.first?.decodedFromUrl(),
                        let value = pairArr.last?.decodedFromUrl() else {
                            continue
                    }
                    pairs[key] = value
                }
                let pairJSON = JSON(pairs)
                let jsonb = pairJSON["player_response"].rawString()?.toJSON()
                if JSON(jsonb)["streamingData"]["formats"].exists()
                {
                    let rawInfo = JSON(jsonb)["streamingData"]["formats"]
                    if rawInfo[0]["url"].exists()
                    {
                        let urls = rawInfo.arrayValue.reversed().compactMap { $0["url"].stringValue }
                        completion(self.firstPlayable(from: urls)!, true)
                    }
                    else
                    {
                        completion(" Unable to get youtube link", false)
                    }
                }
                else
                {
                    completion(" Unable to get youtube link", false)
                }
            }
        }
    }`


//then you can call 
`getYoutubeVideoLink (youtubeLink: "https://www.youtube.com/watch?v=u7Fc8gL9ZTs") { (url, status) in
                if status{
                    DispatchQueue.main.async() {
                         let player  : AVPlayer  = AVPlayer(url: URL(string: url)!)
                        let playerViewController = AVPlayerViewController()
                        playerViewController.player = player
                        self.present(playerViewController, animated: true, completion: {
                            playerViewController.player!.play()
                        })
                     }
                }
                else
                {    
                    print("unable to play video")
                }
              }`


> Note: This code works with all public youtube videos which doesn't have any copyright claim, plz get the missing extension code from https://github.com/devandsev/YoutubeDirectLinkExtractor/tree/develop/Sources

**Comment by buttcmd** [comment]
I have remake the info extraction: https://github.com/devandsev/YoutubeDirectLinkExtractor/pull/11#issuecomment-590574516

while @devandsev checks the pull request it is in my fork

**Comment by devandsev** [comment]
Resolved in #11
