### ISSUE TITLE
unable to install via SPM

### ISSUE THREAD

**Issue by nysander** [devandsev/YoutubeDirectLinkExtractor#12]
when I try to add this package to my project I get this error:

/Users/.../Library/Developer/Xcode/DerivedData/.../SourcePackages/checkouts/YoutubeDirectLinkExtractor/Package.swift: Source files for target YoutubeDirectLinkExtractor should be located under 'Sources/YoutubeDirectLinkExtractor', or a custom sources path can be set with the 'path' property in Package.swift

**Comment by devandsev** [comment]
Issue is resolved in the latest release 0.3.1, fixed in 5017009f15ac6d659d26678556c80e5a74868aa2

**Comment by nysander** [comment]
Thank you
