### ISSUE TITLE
Error: cantExtractFmtStreamMap

### ISSUE THREAD

**Issue by Senocico** [devandsev/YoutubeDirectLinkExtractor#6]
Hi,
Thank you for this library; it's working flawless, but in some cases, for some YouTube link I receive the following error:

`cantExtractFmtStreamMap`

It is possible to fix this issue? 
Otherwise I need to check another solution for this 😐

**Comment by devandsev** [comment]
Hi!

`cantExtractFmtStreamMap` means that there's no `url_encoded_fmt_stream_map` field in the response. I haven't dug deep enough why it can happen for some videos, and won't be able to work on workaround in the nearest future, sorry.

Techniques for non-standard scenarios are implemented in https://github.com/ytdl-org/youtube-dl/ , maybe this might help.

**Comment by Senocico** [comment]
Hi,
Thank you for your answer!
Meanwhile I changed to this library https://github.com/devandsev/YoutubeDirectLinkExtractor and it works for every single YouTube videos.

**Comment by nysander** [comment]
same here, for every url

**Comment by HoangDinhTho** [comment]
Today, the error cantExtractFmtStreamMap for all video. @all any solution !?

**Comment by buttcmd** [comment]
I have remake the info extraction: https://github.com/devandsev/YoutubeDirectLinkExtractor/pull/11#issuecomment-590574516

while @devandsev checks the pull request it is in my fork

**Comment by devandsev** [comment]
Resolved in #11
